baseurl = "https://troop178.netlify.com/"
DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "Troop 178"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
  subtitle = "Taking scouting further..."
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.png"
  dateFormat = "January 2, 2006"
  commit = false
  rss = false
  comments = true
  readingTime = true
  useHLJS = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "Troop 178"
  website = "yourwebsite.com"

[[menu.main]]
    name = "Calendar"
    url = "calendar/calendar"
    weight = 1
  
[[menu.main]]
    name = "Announcements"
    url = ""
    weight = 2
  
[[menu.main]]
    name = "Troop Information"
    url = "vision"
    weight = 3

[[menu.main]]
    name = "Documents"
    url = "https://drive.google.com/drive/folders/1Zr15AXkaIfc06vqpLnNqu-JYoOTPLnph"
    hrefTargetBlank = true
    weight = 4




